### PR TITLE
HWS: dump Go To action

### PR DESCRIPTION
**Pull request by nvswarren**
Every hit STE ends execution by executing the STE indicated by the hit_addr. Print this as an "Action" so that it's obvious how STEs are chained together.

### CODE REVIEW

**Comment by nvswarren** [comment]
@hamdanigbaria does this change look OK? Thanks.

**Comment by hamdanigbaria** [comment]
Hi,
This change will add go to line for each STE,
We had some arch. convention to order the STE's as the order of their chain,
Also this will do some double info, for example when you have goto FT you will have two info's regarding the goto address.
Till me what you want to do exactly?
if you want for each STE to have the hit address parsed, if so i'll prepare such patch where you get the hit address, but i'll put it in high verbosity (-vvvv)

**Comment by nvswarren** [comment]
> We had some arch. convention to order the STE's as the order of their chain,

In the current dump tool, when there are multiple STEs in a single rule/entry, they are indeed listed in execution order. However, jumps between tables are not necessarily listed in order, and in general cannot be for complex programs, so the dump must explicitly state where to next_table field will jump to, or it will be impossible to trace execution between tables.

> Also this will do some double info, for example when you have goto FT you will have two info's
> regarding the goto address.

I don't see any duplicate information lines with this patch. Or do you just mean that in the added text "Go To: 0xa0000191 (FT: 0x2a)", the destination flow table is represented in two ways; the raw ICM address (0xa0000191) _and_ the FT ID (0x2a)? I guess that we could emit _only_ the FT ID at low verbosity levels, and only include the raw ICM address at a higher verbosity level, or if the mapping from ICM address to FT ID doesn't contain an entry for the ICM address in question. I believe that it should be possible to request both values be decoded/dumped (at least at some verbosity level) so that it's possible to get consistent and complete data about each STE, rather than a format that varies depending on the content.

> Till me what you want to do exactly?

Primarily: We need to be able to follow execution flow between tables. In any given table, it's entirely possible for different entries/rules to jump to different tables/destinations. We need this explicitly represented in the dump so that we don't need to refer to other sources of information for basic reading of the dump.

**Comment by hamdanigbaria** [comment]
In today dump info the jump between tables is represented by the goto FT: <FT ID> action
so the only thing missing and you want it, is to show the ICM address next to the FT ID
we can add the icm address as follows: goto FT <FT ID> (<ICM ADDRESS>)
at -vvv and above

**Comment by nvswarren** [comment]
I'll close this for now. I'm working on something like the following, which will skip the dump when everything is "as expected", but dump exceptions or jumps between tables:
```
        if True: # FIXME: STE is STE n-1:
            # STE n-1: Always dump
            dump_goto = True
        else:
            # STEs 0..n-2: Allow any entry in column matcher
            # FIXME:
            expected_hit_addr = None
            dump_goto = self.hit_addr != expected_hit_addr
        if dump_goto:
            _str += _tabs + 'Go To: '
            obj = _db._term_dest_db.get(self.hit_addr)
            if obj != None:
                _str += ' (' + obj.get("type") + ': ' + obj.get("id") + ')'
            else:
                _str += self.hit_addr
            _str += '\n'
```

**Pull request closed without merging**
